function getMockUp() {
  return new Promise((resolve, reject) => {
    resolve({
      data: mockup,
      randomNumber: "0 (mockupData)",
    });
  });
}

export default getMockUp;

const mockup = [
  {
    kenteken: "XV250S",
    voertuigsoort: "Personenauto",
    merk: "FORD",
    handelsbenaming: "FIESTA",
    vervaldatum_apk: "20210329",
    datum_tenaamstelling: "20190330",
    bruto_bpm: "2986",
    inrichting: "hatchback",
    aantal_zitplaatsen: "5",
    eerste_kleur: "ROOD",
    tweede_kleur: "Niet geregistreerd",
    aantal_cilinders: "4",
    cilinderinhoud: "1596",
    massa_ledig_voertuig: "945",
    toegestane_maximum_massa_voertuig: "1500",
    massa_rijklaar: "1045",
    maximum_massa_trekken_ongeremd: "520",
    maximum_trekken_massa_geremd: "900",
    zuinigheidslabel: "B",
    datum_eerste_toelating: "20090414",
    datum_eerste_afgifte_nederland: "20190330",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "Ja",
    aantal_deuren: "2",
    aantal_wielen: "4",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "0",
    europese_voertuigcategorie: "M1",
    technische_max_massa_voertuig: "1500",
    type: "JA8",
    typegoedkeuringsnummer: "e9*2001/116*0069*02",
    variant: "HXJA1G",
    uitvoering: "5BDBAC",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.08",
    wielbasis: "249",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "2400",
    aantal_rolstoelplaatsen: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "F164BR",
    voertuigsoort: "Bromfiets",
    merk: "PIAGGIO",
    handelsbenaming: "C38",
    datum_tenaamstelling: "20110623",
    inrichting: "N.v.t.",
    aantal_zitplaatsen: "2",
    eerste_kleur: "N.v.t.",
    tweede_kleur: "N.v.t.",
    aantal_cilinders: "1",
    cilinderinhoud: "50",
    massa_ledig_voertuig: "102",
    toegestane_maximum_massa_voertuig: "290",
    massa_rijklaar: "113",
    datum_eerste_toelating: "20110623",
    datum_eerste_afgifte_nederland: "20110623",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "Ja",
    maximale_constructiesnelheid_brom_snorfiets: "25",
    vermogen_brom_snorfiets: "1.7",
    aantal_deuren: "0",
    aantal_wielen: "2",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "0",
    europese_voertuigcategorie: "L1",
    europese_voertuigcategorie_toevoeging: "e",
    europese_uitvoeringcategorie_toevoeging: "e",
    plaats_chassisnummer: "r. frame onder zadel",
    technische_max_massa_voertuig: "290",
    typegoedkeuringsnummer: "e3*2002/24*0565*01",
    variant: "9",
    uitvoering: "00",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.02",
    wielbasis: "129",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "WDFF66",
    voertuigsoort: "Aanhangwagen",
    merk: "ANSSEMS",
    handelsbenaming: "BS1",
    datum_tenaamstelling: "20030805",
    inrichting: "open wagen",
    eerste_kleur: "N.v.t.",
    tweede_kleur: "N.v.t.",
    massa_ledig_voertuig: "320",
    toegestane_maximum_massa_voertuig: "1300",
    datum_eerste_toelating: "20010912",
    datum_eerste_afgifte_nederland: "20010912",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "N.v.t.",
    laadvermogen: "980",
    aantal_deuren: "0",
    aantal_wielen: "0",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "368",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "178",
    europese_voertuigcategorie: "O2",
    plaats_chassisnummer: "r. op trekdriehoek 060 cm a. hart koppeling",
    technische_max_massa_voertuig: "1300",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    wielbasis: "0",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "69PHXL",
    voertuigsoort: "Personenauto",
    merk: "TOYOTA",
    handelsbenaming: "TOYOTA RAV4",
    vervaldatum_apk: "20201201",
    datum_tenaamstelling: "20040702",
    bruto_bpm: "8316",
    inrichting: "MPV",
    aantal_zitplaatsen: "5",
    eerste_kleur: "GRIJS",
    tweede_kleur: "Niet geregistreerd",
    aantal_cilinders: "4",
    cilinderinhoud: "1998",
    massa_ledig_voertuig: "1245",
    toegestane_maximum_massa_voertuig: "1825",
    massa_rijklaar: "1345",
    maximum_massa_trekken_ongeremd: "640",
    maximum_trekken_massa_geremd: "1500",
    zuinigheidslabel: "F",
    datum_eerste_toelating: "20040702",
    datum_eerste_afgifte_nederland: "20040702",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "Ja",
    aantal_deuren: "5",
    aantal_wielen: "4",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "0",
    europese_voertuigcategorie: "M1",
    plaats_chassisnummer: "op bodemplaat by r. voorzitting",
    technische_max_massa_voertuig: "1825",
    typegoedkeuringsnummer: "e6*2001/116*0070*04",
    variant: "ACA21(W)",
    uitvoering: "ACA21L-AWMNKW(2E)",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.08",
    wielbasis: "249",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Ja",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "3325",
    aantal_rolstoelplaatsen: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "43FRF5",
    voertuigsoort: "Bromfiets",
    merk: "PIAGGIO",
    handelsbenaming: "SI",
    datum_tenaamstelling: "20170317",
    inrichting: "N.v.t.",
    eerste_kleur: "N.v.t.",
    tweede_kleur: "N.v.t.",
    cilinderinhoud: "50",
    massa_ledig_voertuig: "52",
    massa_rijklaar: "59",
    datum_eerste_toelating: "20050831",
    datum_eerste_afgifte_nederland: "20060603",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "Ja",
    maximale_constructiesnelheid_brom_snorfiets: "45",
    vermogen_brom_snorfiets: "1.29",
    aantal_deuren: "0",
    aantal_wielen: "2",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "0",
    europese_voertuigcategorie: "L1",
    europese_voertuigcategorie_toevoeging: "e",
    europese_uitvoeringcategorie_toevoeging: "e",
    plaats_chassisnummer: "t.p.v. balhoofd",
    technische_max_massa_voertuig: "0",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.02",
    wielbasis: "109",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "PV038X",
    voertuigsoort: "Personenauto",
    merk: "BMW",
    handelsbenaming: "X4 XDRIVE20D",
    vervaldatum_apk: "20201128",
    datum_tenaamstelling: "20170926",
    bruto_bpm: "8414",
    inrichting: "sedan",
    aantal_zitplaatsen: "5",
    eerste_kleur: "ZWART",
    tweede_kleur: "Niet geregistreerd",
    aantal_cilinders: "4",
    cilinderinhoud: "1995",
    massa_ledig_voertuig: "1720",
    toegestane_maximum_massa_voertuig: "2335",
    massa_rijklaar: "1820",
    maximum_massa_trekken_ongeremd: "750",
    maximum_trekken_massa_geremd: "2000",
    zuinigheidslabel: "D",
    datum_eerste_toelating: "20151126",
    datum_eerste_afgifte_nederland: "20170926",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    catalogusprijs: "80072",
    wam_verzekerd: "Ja",
    aantal_deuren: "4",
    aantal_wielen: "4",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "467",
    breedte: "0",
    europese_voertuigcategorie: "M1",
    plaats_chassisnummer: "r. motorruimte",
    technische_max_massa_voertuig: "2335",
    type: "X3",
    typegoedkeuringsnummer: "e1*2007/46*0512*15",
    variant: "XX11",
    uitvoering: "6A250000",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.08",
    wielbasis: "281",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "4435",
    aantal_rolstoelplaatsen: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "FZ082F",
    voertuigsoort: "Bromfiets",
    merk: "SYM",
    handelsbenaming: "AV05W",
    datum_tenaamstelling: "20110719",
    inrichting: "N.v.t.",
    aantal_zitplaatsen: "2",
    eerste_kleur: "N.v.t.",
    tweede_kleur: "N.v.t.",
    aantal_cilinders: "1",
    cilinderinhoud: "50",
    massa_ledig_voertuig: "95",
    toegestane_maximum_massa_voertuig: "249",
    massa_rijklaar: "99",
    datum_eerste_toelating: "20081028",
    datum_eerste_afgifte_nederland: "20081028",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "Ja",
    maximale_constructiesnelheid_brom_snorfiets: "45",
    vermogen_brom_snorfiets: "2.35",
    aantal_deuren: "0",
    aantal_wielen: "2",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "0",
    europese_voertuigcategorie: "L1",
    europese_voertuigcategorie_toevoeging: "e",
    europese_uitvoeringcategorie_toevoeging: "e",
    plaats_chassisnummer: "tegen framebuis onder balhoofd",
    technische_max_massa_voertuig: "249",
    type: "AV05W",
    typegoedkeuringsnummer: "e4*2002/24*1412*00",
    variant: "N/A",
    uitvoering: "AV05W-6",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.02",
    wielbasis: "132",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "0",
    aantal_rolstoelplaatsen: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "PL089G",
    voertuigsoort: "Personenauto",
    merk: "VOLKSWAGEN",
    handelsbenaming: "CADDY",
    vervaldatum_apk: "20210809",
    datum_tenaamstelling: "20170809",
    bruto_bpm: "7812",
    inrichting: "voor rolstoelen toegankelijk voertuig",
    aantal_zitplaatsen: "5",
    eerste_kleur: "GRIJS",
    tweede_kleur: "Niet geregistreerd",
    aantal_cilinders: "4",
    cilinderinhoud: "1197",
    massa_ledig_voertuig: "1386",
    toegestane_maximum_massa_voertuig: "2180",
    massa_rijklaar: "1486",
    maximum_massa_trekken_ongeremd: "710",
    maximum_trekken_massa_geremd: "1400",
    zuinigheidslabel: "C",
    datum_eerste_toelating: "20130805",
    datum_eerste_afgifte_nederland: "20170809",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    catalogusprijs: "28861",
    wam_verzekerd: "Ja",
    aantal_deuren: "4",
    aantal_wielen: "4",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "0",
    breedte: "0",
    europese_voertuigcategorie: "M1",
    plaats_chassisnummer: "r. a. kofferruimte",
    technische_max_massa_voertuig: "2180",
    type: "2K",
    typegoedkeuringsnummer: "e1*2001/116*0252*36",
    variant: "ACCBZBX01",
    uitvoering: "N0J2FM5FM5AH016N1STVR07MJ",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.05",
    wielbasis: "268",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "3402",
    aantal_rolstoelplaatsen: "1",
    maximum_ondersteunende_snelheid: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "JX569L",
    voertuigsoort: "Personenauto",
    merk: "PEUGEOT",
    handelsbenaming: "2008",
    vervaldatum_apk: "20220630",
    datum_tenaamstelling: "20200818",
    bruto_bpm: "3504",
    inrichting: "stationwagen",
    aantal_zitplaatsen: "5",
    eerste_kleur: "ZWART",
    tweede_kleur: "Niet geregistreerd",
    aantal_cilinders: "3",
    cilinderinhoud: "1199",
    massa_ledig_voertuig: "1020",
    toegestane_maximum_massa_voertuig: "1582",
    massa_rijklaar: "1120",
    maximum_massa_trekken_ongeremd: "560",
    maximum_trekken_massa_geremd: "1100",
    zuinigheidslabel: "C",
    datum_eerste_toelating: "20160630",
    datum_eerste_afgifte_nederland: "20160630",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    catalogusprijs: "20280",
    wam_verzekerd: "Ja",
    aantal_deuren: "4",
    aantal_wielen: "4",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "416",
    breedte: "0",
    europese_voertuigcategorie: "M1",
    plaats_chassisnummer: "in motorruimte v.",
    technische_max_massa_voertuig: "1582",
    type: "C",
    typegoedkeuringsnummer: "e2*2007/46*0070*30",
    variant: "UHMZ",
    uitvoering: "6",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.05",
    wielbasis: "254",
    export_indicator: "Nee",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "2362",
    aantal_rolstoelplaatsen: "0",
    maximum_ondersteunende_snelheid: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
  {
    kenteken: "PK984T",
    voertuigsoort: "Personenauto",
    merk: "LOTUS",
    handelsbenaming: "ELISE",
    vervaldatum_apk: "20191003",
    datum_tenaamstelling: "20170812",
    bruto_bpm: "8826",
    inrichting: "cabriolet",
    aantal_zitplaatsen: "2",
    eerste_kleur: "GRIJS",
    tweede_kleur: "Niet geregistreerd",
    aantal_cilinders: "4",
    cilinderinhoud: "1796",
    massa_ledig_voertuig: "749",
    toegestane_maximum_massa_voertuig: "1044",
    massa_rijklaar: "849",
    zuinigheidslabel: "D",
    datum_eerste_toelating: "20010901",
    datum_eerste_afgifte_nederland: "20170812",
    wacht_op_keuren: "Geen verstrekking in Open Data",
    wam_verzekerd: "Nee",
    aantal_deuren: "2",
    aantal_wielen: "4",
    afstand_hart_koppeling_tot_achterzijde_voertuig: "0",
    afstand_voorzijde_voertuig_tot_hart_koppeling: "0",
    lengte: "379",
    breedte: "0",
    europese_voertuigcategorie: "M1",
    plaats_chassisnummer: "tegen r. balk onder voorwielscherm",
    technische_max_massa_voertuig: "1044",
    typegoedkeuringsnummer: "e4*98/14*0008*18",
    variant: "5",
    uitvoering: "A",
    volgnummer_wijziging_eu_typegoedkeuring: "0",
    vermogen_massarijklaar: "0.11",
    wielbasis: "230",
    export_indicator: "Ja",
    openstaande_terugroepactie_indicator: "Nee",
    taxi_indicator: "Nee",
    maximum_massa_samenstelling: "0",
    aantal_rolstoelplaatsen: "0",
    api_gekentekende_voertuigen_assen:
      "https://opendata.rdw.nl/resource/3huj-srit.json",
    api_gekentekende_voertuigen_brandstof:
      "https://opendata.rdw.nl/resource/8ys7-d773.json",
    api_gekentekende_voertuigen_carrosserie:
      "https://opendata.rdw.nl/resource/vezc-m2t6.json",
    api_gekentekende_voertuigen_carrosserie_specifiek:
      "https://opendata.rdw.nl/resource/jhie-znh9.json",
    api_gekentekende_voertuigen_voertuigklasse:
      "https://opendata.rdw.nl/resource/kmfi-hrps.json",
  },
];
